# Configuration file for Travis CI, see https://docs.travis-ci.com
# sudo is required for chrome installation. A different approach without sudo will be done later.
sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
env:
  global:
  - NODE_VERSION: 6
  - CHROME_BIN: chromium-browser
  - MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn #see https://docs.travis-ci.com/user/common-build-problems/#Log-Length-exceeded and https://blogs.itemis.com/en/in-a-nutshell-removing-artifact-messages-from-maven-log-output
before_script:
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start #start xvfb so that we can start Firefox, see https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - npm install -g @angular/cli@1.0.3
before_install:
- nvm install $NODE_VERSION
script:
- (cd backend && ./build.sh)
  && (cd api && ./build.sh)
  && (cd frontend && ./build.sh)
  && (cd acceptance-tests && ./build.sh && ./upload-serenity-reports.sh)
  && (cd services/flightinformation && ./build.sh)
  && (cd services/educama-supplier-simulator-backend && ./build.sh)
  && (cd services/educama-supplier-simulator-frontend && ./build.sh)
addons:
  #Browser is used by the acceptance tests
  firefox: '42.0'
  #Browser is used for angular unit tests
  chrome: stable
cache:
  timeout: 604800 #1 week
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  username: educama-core@novatec-gmbh.de
  password:
    secure: T3gblw+Bikg+4ELFsqHxSV96RngijEJqkfhsjkrprU4xff0YGiKgGWTcWmemAYxdlKogL3u6FT0TcFP95hdYDXUWggtzZKZGq6LLALJHRjITDaIXfq1xvDhaC8Q54t28UKM+mH8aO7XxnUOjrlHSScJNvVFDtJKorvf7KJsz/0rzEc7km7b0Yrnonj2QlPwycBPMBYTgo5XDuPMMskJ/fJG4Fi/MYLYlEUeyb/QCJawmKcbrjItDoMxVtmZnsHKE5Dyej+aGQj906dPCUTMN1cS4bi/vpQBhtGgo9FqD5QQm3fvYlmmZsjvMUHh1jLO8peBvuRpcUkBuZ/naLYy9mXmy1KfgbyPPczG1wNq3sl7mgvxdbypQuhiedgJGY6j66FEL9BQPJdPdoQ4u2faBwCY27mQBcI0DfEwfqzpYyv2Ke7zmv5O6eobSNj9i/W7+EhackWqEZEf8Hxh89/UrGYw00qLP6mUPI3IRub6Ds6kQYHOcmV4KPK3iRNb9+mFQYgftHzyHIuZUmskbE5ccsMXRm813ommeOq25XH/DbO1LvOavf3KQUoEc3+k6fLlp4B3OU07+dlhPhPXa76nGESofgXKtswGrXx17ypKfNNBpBqsenn7VeZUU2blgCn/bfAreRsCKvCxx5FmFoyt/+oeamHrw5oh/6Uz+qdO3yHk=
  api: https://api.ng.bluemix.net
  organization: '"NovaTec Consulting GmbH"'
  space: Educama-Development
  manifest: manifests/development.yml
  on:
    repo: Educama/Showcase
